apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper-deployment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: zookeeper
    spec:
      restartPolicy: Never
      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: task-zookeeper-pv-claim
      containers: 
      - name: zookeeper
        image: zookeeper:latest
        volumeMounts:
        - name: vol
          mountPath: /store
        ports:
        - name: zookeeper-port
          containerPort: 2181
        env:
          - name: ZOO_MY_ID
            valueFrom: 
              configMapKeyRef:
                name: zookeeper-config
                key: zooMyId
          - name: ZOO_LOG_DIR
            valueFrom: 
              configMapKeyRef:
                name: zookeeper-config
                key: zooLogDir
          - name: ZOO_DATA_DIR
            valueFrom: 
              configMapKeyRef:
                name: zookeeper-config
                key: zooDataDir
          - name: ZOO_DATA_LOG_DIR
            valueFrom: 
              configMapKeyRef:
                name: zookeeper-config
                key: zooDataLogDir
          - name: ZOO_PORT
            valueFrom: 
              configMapKeyRef:
                name: zookeeper-config
                key: zooPort
