apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: zookeeper-ss
spec:
  selector:
    matchLabels:
      app: zookeeper-app # has to match .spec.template.metadata.labels
  serviceName: "zookeeper-service"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: zookeeper-app # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
      - name: volzookeeper
        persistentVolumeClaim:
          claimName: task-zookeeper-pv-claim
      containers:
      - name: zookeeper
        image: zookeeper:latest
        volumeMounts:
        - name: volzookeeper
          mountPath: /store
        ports:
        - name: zookeeper-port
          containerPort: 2181
        env:
          - name: ZOO_MY_ID
            valueFrom:
              configMapKeyRef:
                name: zookeeper-config
                key: zooMyId
          - name: ZOO_LOG_DIR
            valueFrom:
              configMapKeyRef:
                name: zookeeper-config
                key: zooLogDir
          - name: ZOO_DATA_DIR
            valueFrom:
              configMapKeyRef:
                name: zookeeper-config
                key: zooDataDir
          - name: ZOO_DATA_LOG_DIR
            valueFrom:
              configMapKeyRef:
                name: zookeeper-config
                key: zooDataLogDir
          - name: ZOO_PORT
            valueFrom:
              configMapKeyRef:
                name: zookeeper-config
                key: zooPort
