apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  ports:
  - port: 32181
    targetPort: 32181
    nodePort: 32181
    protocol: TCP
  selector:
    app: zookeeper-app
  type: NodePort
