kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zones: us-east-1b, us-east-1d, us-east-1c
  fsType: ext4
reclaimPolicy: Retain
mountOptions:
  - debug
